### ISSUE TITLE
How to install the library in google colab notebook?

### ISSUE THREAD

**Issue by Redevic** [libffcv/ffcv#118]
Hi, i try install ffcv in google colab using 
!pip install ffcv 
but i get an error :
ERROR: Could not find a version that satisfies the requirement ffcv (from versions: 0.0.1, 0.0.2, 0.0.3rc1, 0.0.3)
ERROR: No matching distribution found for ffcv.
![image](https://user-images.githubusercontent.com/98649930/151663478-1bc2c838-32f5-4c2c-a85e-90e870e663c3.png)

**Comment by GuillaumeLeclerc** [comment]
Hello,

Unfortunately this is beyond our control. Colab only works with python 3.7.2 and FFCV requires at least 3.8. There is no change we could do to support 3.7 because `multiprocessing.shared_memory` was released as part of the standard library for python `3.8` As soon as Colab updates to 3.8 you should re-open this issue and we will provide an example

**Comment by Redevic** [comment]
Got it. Thank you very much for the clarification

Сб, 29 янв. 2022 г. в 18:41, Guillaume Leclerc ***@***.***>:

**Comment by 1ucky40nc3** [comment]
It seems that colab has switched to python=3.8.15. Here is a [gist](https://gist.github.com/1ucky40nc3/85e73031440cca639571506a6e0c5016) and a screenshot:
![image](https://user-images.githubusercontent.com/64500884/204911409-7299d739-d4c6-4f6e-9811-21b3042b8001.png)
