### ISSUE TITLE
Albumentations

### ISSUE THREAD

**Issue by RocketFlash** [libffcv/ffcv#201]
Hi! Is it possible to use ffcv with albumentations transformations ? As I understand .beton files consist of already transformed and saved instances. Is it possible to use transformations in real time manner?

**Comment by GuillaumeLeclerc** [comment]
`.beton` files do *not* consist of already transformed and saved instances otherwise it would be impossible to do random augmentations at train.

Some people have used albumentations augmentations with FFCV but I would recommend against if your goal is pure performance as they will only run with single worker. Augmentations are usually very simple procedure (a couple of lines of numpy). I recommend implementing them in numpy and integrate them as `FFCV` transforms, this will get the best performance
