### ISSUE TITLE
Can ffcv be used for other DL framework？

### ISSUE THREAD

**Issue by renmada** [libffcv/ffcv#46]
Does it works that just use ffcv as dataloader?

**Comment by GuillaumeLeclerc** [comment]
We haven't personally experimented but there is no reason why it wouldn't. Indeed because when the loader produces a batch it's already on the GPU and copied, you can just convert that tensor and do what you feel like as long as you work in the default CUDA stream there should be no issues.

https://docs.cupy.dev/en/stable/user_guide/interoperability.html contains useful information on how to convert GPU tensors cost-free (disclaimer there might be better ways)
